version: "3.8"

services:
  web:
    build: ./Client
    ports:
      - 5173
    networks:
      - mern-ecommerce-website
    tty: true
  api:
    build: ./Server
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - mern-ecommerce-website
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    networks:
      - mern-ecommerce-website
    volumes:
      - mern-ecommerce-website:/data/db
  nginx:
    build: ./NginX
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - mern-ecommerce-website
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - mern-ecommerce-website


networks:
  mern-ecommerce-website:
    driver: bridge

volumes:  
  mern-ecommerce-website:
    driver: local
