version: "3.8"

services:
  api:
    build: ./Server
    ports:
      - 3000
    depends_on:
      - db
    networks:
      - mern-ecommerce-website
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017
    networks:
      - mern-ecommerce-website
    volumes:
      - mern-ecommerce-website:/data/db
  nginx:
    build: ./Client
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - mern-ecommerce-website
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379
    networks:
      - mern-ecommerce-website


networks:
  mern-ecommerce-website:
    driver: bridge

volumes:  
  mern-ecommerce-website:
    driver: local
